/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Id = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'fuel' : IDL.Null,
  'mechanic' : IDL.Null,
  'towing' : IDL.Null,
});
export const NewAssistanceRequest = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'description' : IDL.Text,
  'requestType' : ServiceType,
});
export const NewProviderProfile = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'serviceType' : ServiceType,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const ProviderProfile = IDL.Record({
  'id' : Id,
  'isApproved' : IDL.Bool,
  'serviceType' : ServiceType,
  'ratingCount' : IDL.Nat,
  'userId' : IDL.Principal,
  'isAvailable' : IDL.Bool,
  'rating' : IDL.Float64,
  'location' : Location,
});
export const Rating = IDL.Nat;
export const RatingEntry = IDL.Record({
  'id' : Id,
  'requestId' : Id,
  'score' : Rating,
  'comment' : IDL.Text,
  'providerId' : Id,
});
export const RequestStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const AssistanceRequest = IDL.Record({
  'id' : Id,
  'status' : RequestStatus,
  'userId' : IDL.Principal,
  'description' : IDL.Text,
  'userLocation' : Location,
  'assignedProviderId' : IDL.Opt(Id),
  'requestType' : ServiceType,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'provider' : IDL.Null,
  'user' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const NewRating = IDL.Record({
  'requestId' : Id,
  'score' : Rating,
  'comment' : IDL.Text,
  'providerId' : Id,
});
export const UpdateProviderProfile = IDL.Record({
  'lat' : IDL.Opt(IDL.Float64),
  'lng' : IDL.Opt(IDL.Float64),
  'serviceType' : IDL.Opt(ServiceType),
  'isAvailable' : IDL.Opt(IDL.Bool),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveProvider' : IDL.Func([Id], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAssistanceRequest' : IDL.Func([NewAssistanceRequest], [Id], []),
  'createProviderProfile' : IDL.Func([NewProviderProfile], [Id], []),
  'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
  'getAllRatings' : IDL.Func([], [IDL.Vec(RatingEntry)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(AssistanceRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProvider' : IDL.Func([Id], [ProviderProfile], ['query']),
  'getProviderRatings' : IDL.Func([Id], [IDL.Vec(RatingEntry)], ['query']),
  'getRequest' : IDL.Func([Id], [AssistanceRequest], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRating' : IDL.Func([NewRating], [Id], []),
  'updateProviderProfile' : IDL.Func([Id, UpdateProviderProfile], [], []),
  'updateRequestStatus' : IDL.Func([Id, RequestStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Id = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'fuel' : IDL.Null,
    'mechanic' : IDL.Null,
    'towing' : IDL.Null,
  });
  const NewAssistanceRequest = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'description' : IDL.Text,
    'requestType' : ServiceType,
  });
  const NewProviderProfile = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'serviceType' : ServiceType,
  });
  const Location = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const ProviderProfile = IDL.Record({
    'id' : Id,
    'isApproved' : IDL.Bool,
    'serviceType' : ServiceType,
    'ratingCount' : IDL.Nat,
    'userId' : IDL.Principal,
    'isAvailable' : IDL.Bool,
    'rating' : IDL.Float64,
    'location' : Location,
  });
  const Rating = IDL.Nat;
  const RatingEntry = IDL.Record({
    'id' : Id,
    'requestId' : Id,
    'score' : Rating,
    'comment' : IDL.Text,
    'providerId' : Id,
  });
  const RequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const AssistanceRequest = IDL.Record({
    'id' : Id,
    'status' : RequestStatus,
    'userId' : IDL.Principal,
    'description' : IDL.Text,
    'userLocation' : Location,
    'assignedProviderId' : IDL.Opt(Id),
    'requestType' : ServiceType,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'provider' : IDL.Null,
    'user' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const NewRating = IDL.Record({
    'requestId' : Id,
    'score' : Rating,
    'comment' : IDL.Text,
    'providerId' : Id,
  });
  const UpdateProviderProfile = IDL.Record({
    'lat' : IDL.Opt(IDL.Float64),
    'lng' : IDL.Opt(IDL.Float64),
    'serviceType' : IDL.Opt(ServiceType),
    'isAvailable' : IDL.Opt(IDL.Bool),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveProvider' : IDL.Func([Id], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAssistanceRequest' : IDL.Func([NewAssistanceRequest], [Id], []),
    'createProviderProfile' : IDL.Func([NewProviderProfile], [Id], []),
    'getAllProviders' : IDL.Func([], [IDL.Vec(ProviderProfile)], ['query']),
    'getAllRatings' : IDL.Func([], [IDL.Vec(RatingEntry)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(AssistanceRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProvider' : IDL.Func([Id], [ProviderProfile], ['query']),
    'getProviderRatings' : IDL.Func([Id], [IDL.Vec(RatingEntry)], ['query']),
    'getRequest' : IDL.Func([Id], [AssistanceRequest], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRating' : IDL.Func([NewRating], [Id], []),
    'updateProviderProfile' : IDL.Func([Id, UpdateProviderProfile], [], []),
    'updateRequestStatus' : IDL.Func([Id, RequestStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };