/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssistanceRequest {
  'id' : Id,
  'status' : RequestStatus,
  'userId' : Principal,
  'description' : string,
  'userLocation' : Location,
  'assignedProviderId' : [] | [Id],
  'requestType' : ServiceType,
}
export type Id = bigint;
export interface Location { 'lat' : number, 'lng' : number }
export interface NewAssistanceRequest {
  'lat' : number,
  'lng' : number,
  'description' : string,
  'requestType' : ServiceType,
}
export interface NewProviderProfile {
  'lat' : number,
  'lng' : number,
  'serviceType' : ServiceType,
}
export interface NewRating {
  'requestId' : Id,
  'score' : Rating,
  'comment' : string,
  'providerId' : Id,
}
export interface ProviderProfile {
  'id' : Id,
  'isApproved' : boolean,
  'serviceType' : ServiceType,
  'ratingCount' : bigint,
  'userId' : Principal,
  'isAvailable' : boolean,
  'rating' : number,
  'location' : Location,
}
export type Rating = bigint;
export interface RatingEntry {
  'id' : Id,
  'requestId' : Id,
  'score' : Rating,
  'comment' : string,
  'providerId' : Id,
}
export type RequestStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export type Role = { 'admin' : null } |
  { 'provider' : null } |
  { 'user' : null };
export type ServiceType = { 'fuel' : null } |
  { 'mechanic' : null } |
  { 'towing' : null };
export interface UpdateProviderProfile {
  'lat' : [] | [number],
  'lng' : [] | [number],
  'serviceType' : [] | [ServiceType],
  'isAvailable' : [] | [boolean],
}
export interface UserProfile {
  'name' : string,
  'role' : Role,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveProvider' : ActorMethod<[Id], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAssistanceRequest' : ActorMethod<[NewAssistanceRequest], Id>,
  'createProviderProfile' : ActorMethod<[NewProviderProfile], Id>,
  'getAllProviders' : ActorMethod<[], Array<ProviderProfile>>,
  'getAllRatings' : ActorMethod<[], Array<RatingEntry>>,
  'getAllRequests' : ActorMethod<[], Array<AssistanceRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProvider' : ActorMethod<[Id], ProviderProfile>,
  'getProviderRatings' : ActorMethod<[Id], Array<RatingEntry>>,
  'getRequest' : ActorMethod<[Id], AssistanceRequest>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRating' : ActorMethod<[NewRating], Id>,
  'updateProviderProfile' : ActorMethod<[Id, UpdateProviderProfile], undefined>,
  'updateRequestStatus' : ActorMethod<[Id, RequestStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];