/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    lat: number;
    lng: number;
}
export interface UserProfile {
    name: string;
    role: Role;
    email: string;
    phone: string;
}
export type Rating = bigint;
export interface NewRating {
    requestId: Id;
    score: Rating;
    comment: string;
    providerId: Id;
}
export interface AssistanceRequest {
    id: Id;
    status: RequestStatus;
    userId: Principal;
    description: string;
    userLocation: Location;
    assignedProviderId?: Id;
    requestType: ServiceType;
}
export interface RatingEntry {
    id: Id;
    requestId: Id;
    score: Rating;
    comment: string;
    providerId: Id;
}
export type Id = bigint;
export interface NewProviderProfile {
    lat: number;
    lng: number;
    serviceType: ServiceType;
}
export interface UpdateProviderProfile {
    lat?: number;
    lng?: number;
    serviceType?: ServiceType;
    isAvailable?: boolean;
}
export interface ProviderProfile {
    id: Id;
    isApproved: boolean;
    serviceType: ServiceType;
    ratingCount: bigint;
    userId: Principal;
    isAvailable: boolean;
    rating: number;
    location: Location;
}
export interface NewAssistanceRequest {
    lat: number;
    lng: number;
    description: string;
    requestType: ServiceType;
}
export enum RequestStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    accepted = "accepted",
    inProgress = "inProgress"
}
export enum Role {
    admin = "admin",
    provider = "provider",
    user = "user"
}
export enum ServiceType {
    fuel = "fuel",
    mechanic = "mechanic",
    towing = "towing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveProvider(id: Id): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAssistanceRequest(input: NewAssistanceRequest): Promise<Id>;
    createProviderProfile(input: NewProviderProfile): Promise<Id>;
    getAllProviders(): Promise<Array<ProviderProfile>>;
    getAllRatings(): Promise<Array<RatingEntry>>;
    getAllRequests(): Promise<Array<AssistanceRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProvider(id: Id): Promise<ProviderProfile>;
    getProviderRatings(providerId: Id): Promise<Array<RatingEntry>>;
    getRequest(requestId: Id): Promise<AssistanceRequest>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitRating(input: NewRating): Promise<Id>;
    updateProviderProfile(id: Id, input: UpdateProviderProfile): Promise<void>;
    updateRequestStatus(requestId: Id, status: RequestStatus): Promise<void>;
}
import type { AssistanceRequest as _AssistanceRequest, Id as _Id, Location as _Location, NewAssistanceRequest as _NewAssistanceRequest, NewProviderProfile as _NewProviderProfile, ProviderProfile as _ProviderProfile, RequestStatus as _RequestStatus, Role as _Role, ServiceType as _ServiceType, UpdateProviderProfile as _UpdateProviderProfile, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveProvider(arg0: Id): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveProvider(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAssistanceRequest(arg0: NewAssistanceRequest): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssistanceRequest(to_candid_NewAssistanceRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssistanceRequest(to_candid_NewAssistanceRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProviderProfile(arg0: NewProviderProfile): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.createProviderProfile(to_candid_NewProviderProfile_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProviderProfile(to_candid_NewProviderProfile_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllProviders(): Promise<Array<ProviderProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProviders();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProviders();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRatings(): Promise<Array<RatingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRatings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRatings();
            return result;
        }
    }
    async getAllRequests(): Promise<Array<AssistanceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRequests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRequests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProvider(arg0: Id): Promise<ProviderProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvider(arg0);
                return from_candid_ProviderProfile_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvider(arg0);
            return from_candid_ProviderProfile_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderRatings(arg0: Id): Promise<Array<RatingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderRatings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderRatings(arg0);
            return result;
        }
    }
    async getRequest(arg0: Id): Promise<AssistanceRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequest(arg0);
                return from_candid_AssistanceRequest_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequest(arg0);
            return from_candid_AssistanceRequest_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n27(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitRating(arg0: NewRating): Promise<Id> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(arg0);
            return result;
        }
    }
    async updateProviderProfile(arg0: Id, arg1: UpdateProviderProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProviderProfile(arg0, to_candid_UpdateProviderProfile_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProviderProfile(arg0, to_candid_UpdateProviderProfile_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRequestStatus(arg0: Id, arg1: RequestStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRequestStatus(arg0, to_candid_RequestStatus_n33(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRequestStatus(arg0, to_candid_RequestStatus_n33(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AssistanceRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AssistanceRequest): AssistanceRequest {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderProfile): ProviderProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Id]): Id | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    isApproved: boolean;
    serviceType: _ServiceType;
    ratingCount: bigint;
    userId: Principal;
    isAvailable: boolean;
    rating: number;
    location: _Location;
}): {
    id: Id;
    isApproved: boolean;
    serviceType: ServiceType;
    ratingCount: bigint;
    userId: Principal;
    isAvailable: boolean;
    rating: number;
    location: Location;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        serviceType: from_candid_ServiceType_n12(_uploadFile, _downloadFile, value.serviceType),
        ratingCount: value.ratingCount,
        userId: value.userId,
        isAvailable: value.isAvailable,
        rating: value.rating,
        location: value.location
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _Id;
    status: _RequestStatus;
    userId: Principal;
    description: string;
    userLocation: _Location;
    assignedProviderId: [] | [_Id];
    requestType: _ServiceType;
}): {
    id: Id;
    status: RequestStatus;
    userId: Principal;
    description: string;
    userLocation: Location;
    assignedProviderId?: Id;
    requestType: ServiceType;
} {
    return {
        id: value.id,
        status: from_candid_RequestStatus_n17(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        description: value.description,
        userLocation: value.userLocation,
        assignedProviderId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.assignedProviderId)),
        requestType: from_candid_ServiceType_n12(_uploadFile, _downloadFile, value.requestType)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _Role;
    email: string;
    phone: string;
}): {
    name: string;
    role: Role;
    email: string;
    phone: string;
} {
    return {
        name: value.name,
        role: from_candid_Role_n23(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fuel: null;
} | {
    mechanic: null;
} | {
    towing: null;
}): ServiceType {
    return "fuel" in value ? ServiceType.fuel : "mechanic" in value ? ServiceType.mechanic : "towing" in value ? ServiceType.towing : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
}): RequestStatus {
    return "cancelled" in value ? RequestStatus.cancelled : "pending" in value ? RequestStatus.pending : "completed" in value ? RequestStatus.completed : "accepted" in value ? RequestStatus.accepted : "inProgress" in value ? RequestStatus.inProgress : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    provider: null;
} | {
    user: null;
}): Role {
    return "admin" in value ? Role.admin : "provider" in value ? Role.provider : "user" in value ? Role.user : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AssistanceRequest>): Array<AssistanceRequest> {
    return value.map((x)=>from_candid_AssistanceRequest_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProviderProfile>): Array<ProviderProfile> {
    return value.map((x)=>from_candid_ProviderProfile_n10(_uploadFile, _downloadFile, x));
}
function to_candid_NewAssistanceRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewAssistanceRequest): _NewAssistanceRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NewProviderProfile_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewProviderProfile): _NewProviderProfile {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_RequestStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): _RequestStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProviderProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProviderProfile): _UpdateProviderProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Role;
    email: string;
    phone: string;
}): {
    name: string;
    role: _Role;
    email: string;
    phone: string;
} {
    return {
        name: value.name,
        role: to_candid_Role_n29(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat?: number;
    lng?: number;
    serviceType?: ServiceType;
    isAvailable?: boolean;
}): {
    lat: [] | [number];
    lng: [] | [number];
    serviceType: [] | [_ServiceType];
    isAvailable: [] | [boolean];
} {
    return {
        lat: value.lat ? candid_some(value.lat) : candid_none(),
        lng: value.lng ? candid_some(value.lng) : candid_none(),
        serviceType: value.serviceType ? candid_some(to_candid_ServiceType_n5(_uploadFile, _downloadFile, value.serviceType)) : candid_none(),
        isAvailable: value.isAvailable ? candid_some(value.isAvailable) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    description: string;
    requestType: ServiceType;
}): {
    lat: number;
    lng: number;
    description: string;
    requestType: _ServiceType;
} {
    return {
        lat: value.lat,
        lng: value.lng,
        description: value.description,
        requestType: to_candid_ServiceType_n5(_uploadFile, _downloadFile, value.requestType)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    serviceType: ServiceType;
}): {
    lat: number;
    lng: number;
    serviceType: _ServiceType;
} {
    return {
        lat: value.lat,
        lng: value.lng,
        serviceType: to_candid_ServiceType_n5(_uploadFile, _downloadFile, value.serviceType)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    provider: null;
} | {
    user: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.provider ? {
        provider: null
    } : value == Role.user ? {
        user: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RequestStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} {
    return value == RequestStatus.cancelled ? {
        cancelled: null
    } : value == RequestStatus.pending ? {
        pending: null
    } : value == RequestStatus.completed ? {
        completed: null
    } : value == RequestStatus.accepted ? {
        accepted: null
    } : value == RequestStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    fuel: null;
} | {
    mechanic: null;
} | {
    towing: null;
} {
    return value == ServiceType.fuel ? {
        fuel: null
    } : value == ServiceType.mechanic ? {
        mechanic: null
    } : value == ServiceType.towing ? {
        towing: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
